### PR TITLE
Anki 2.1.50+ support

### PR DESCRIPTION
**Pull request by hgiesel**
(WIP)

### CODE REVIEW

**Comment by hgiesel** [comment]
Once https://github.com/ankitects/anki/pull/1931 is merged in, you could test this @ijgnd (or you test against the PR).

Only apply categories that surround via a span are tested to work currently, but even this could be uploaded to Ankiweb, as it's much better than nothing working at all :)

**Comment by ijgnd** [comment]
I only did a quick test with the anki branch you mentioned but so far everything seems to work. The add-on is in the best shape it ever was. THANK YOU so much for all your work on it and bringing the add-on into the future.

**Comment by ijgnd** [comment]
Shall I delete this github repo? Yours should be the canonical one. Maybe that's easier for you. If I have code I should send you pull requests.

**Comment by ijgnd** [comment]
Once more thanks for your work on this.

I did some small boring clean up stuff like

- re-added support for pyqt5 so that it should now work with qt5/qt6 (by generating the forms files twice and in each file using a form file I have if "qtmajor ==" ...)
- I deleted my warnings about the template updates. They probably just hurt the add-on.
- I deleted old code meant for conversion of settings from 2019 and early 2020 that no one needs to make it more readable.
- renamed some vars to use underscores

**Comment by hgiesel** [comment]
Great.

Concerning deleting this repo: I don't mind being the one sending PRs :) If you really don't want to work on it anymore in the future, I'd be happy to be the main repo.

Also note that this version now doesn't quite work yet unfortunately, because the Anki PR has not been merged yet. This weekend I unfortunately had to travel, so I couldn't work on it, but I have it on my mind every day :)

**Comment by ijgnd** [comment]
Maybe the simplest solution is to leave it as it is ... I'm pretty sure that I'll quickly merge all your future pull requests. So I'll know about all changes.

**Pull request merged**
