### PR TITLE
Allow web imports to work from any directory name

### PR DESCRIPTION
**Pull request by hgiesel**
This avoids hardcoding the Ankiweb ID, and rather use the subcomponent of __name__ (which happens to be the ankiweb id, when you install it from ankiweb, but not when you link it, which is what I do).

This will help me also look into rangy issues in the future.

Additionally, I avoided putting the commands on the file scope, which gives the file a bit more structure.

### CODE REVIEW

**Comment by ijgnd** [comment]
Thanks.

**Comment by ijgnd** [comment]
Are you interested in maintaining this add-on and taking ownership of the ankiweb listing?

You know the code well, as of today probably better than me. You are a better coder and most importantly you know js. At the moment you work more on it and if you don't have to wait for me merging stuff this could save you some time. This would save me time maintaining. It would be instructive to see how you transform the add-on. When you maintain it the add-on should be around for a long time which is great for me. I think I still have enough add-ons to maintain. And I think I'm stuck on 2.1.26 for the foreseeable future because of recent changes in 2.1.28 - e.g. new notes in the add window no longer get a note-id when you open the window but only after adding the note which breaks my workflow.

I don't have a kofi account but you do. So maybe this would allow to get a few Euros in the long run for you? Though it has only about 8k downloads according to the ankiweb stats - on the other hand it's one of my popular add-ons. I guess removing all my warnings and shortening the description could help ...

I'd appreciate if you would keep my ["hbir" line](https://github.com/ijgnd/anki__editor__apply__font_color__background_color__custom_class__custom_style/issues/27) it the add-on [1] or maybe merge a few lines for me in the future - maybe a custom hook as lovac42's add-on rememorize offers it.

[1] instead of always executing the js function `"hbir_init();"` maybe it should be something like `.replace("MAYBE_HBIR", "hbir_init();" if "1095648795" in mw.addonManager.allAddons() else "")`. That's short though it doesn't check if the add-on is active.

**Comment by hgiesel** [comment]
I really feel honored, thanks.

I wouldn't mind co-maintaining this add-on. Do you have any idea on how to transfer an add-on on Ankiweb? Wouldn't this mean, we have to take down it completely at first?

> And I think I'm stuck on 2.1.26 for the foreseeable future because of recent changes in 2.1.28 - e.g. new notes in the add window no longer get a note-id when you open the window but only after adding the note which breaks my workflow.
May I ask how this breaks your workflow. You certainly know I maintain the "Ze Add Note Id", and I wonder if I could accomodate you there?

> I'd appreciate if you [...]
I think it'd be best if have shared ownership. I think you can set this under "collaborators" in the settings. Basically it would give me the right to clone/push directly to the repository.
This way we can both work on the add-on.
In the case of controversial changes, we could still opt for pull requests instead.

**Comment by ijgnd** [comment]
I didn't know know about the collaboration feature. I just invited you.

btw: do you test your changes also in older versions. At the moment the minimum version I support is 2.1.24. If you also tested with this one I wouldn't have to. I don't care about 2.1.24 and I often just don't support older versions anymore. But since I'm on 2.1.26 at the moment I would prefer if this version was still supported. 

&nbsp;

About transferring an ankiweb listing: I have no internal knowledge, I just have observations: Glutanimate got the syntax highlighting repo reassigned, Arthur the multi-column note editor. On the other hand the popular AwesomeTTS was not transferred. The new maintainer for the new AwesomeTTS seemed be relatively new to Anki - at least I didn't know him before. 

Because of trust/malware problems I guess Damien is hesitant. But getting error messages due to an old unmaintained listing is also not good. So he does it sometimes. I guess since you are a known contributor for over a year that it shouldn't be a problem?

&nbsp;

About my workflow: Thanks for offering to help with the note-id problem. Your "note id" add-on is indeed something I have used.

I also use Anki for note taking for multiple reasons: I know the app, it's just one place to search, and contrary to plain text applications I have multi-line tables and images shown in the editor view, ... So sometimes I have some content in an add window and want to put a reference to an existing note in my collcection. So far I just copied the nid from the note-id field. (For opening these references I use my [link Cards Notes and Preview them in extra window](https://ankiweb.net/shared/info/1423933177)). 

Also my "half-baked ir" add-on adds the note-id of the newly created note in an add window back into the source note. I have a command that copies selected text from one editor into a new add window (with arthur's multiple window add-on) and then with rangy applies a class "extracted" and then it also sets an id for all the selected html tags so that in the long run I could right click a text and run "open selected note in new window". So I need the nid before in the other addcards window the hook "add_cards_did_add_note" is run. Maybe I'll manage to upload it tonight. But because of "Searching, PDF Reading & Note-Taking in Add Dialog" my add-on is much less relevant. 

I guess I could somehow work around this with my [Browser Maximize/Hide Table/Editor](https://ankiweb.net/shared/info/1819291495).

**Comment by ijgnd** [comment]
I forogot: Do you have a better idea about the nid situation? I'll just ask Damien if he can revert to the old behavior - hopefully it's just a small change. But unfortunately I don't know rust so I don't know.

**Comment by hgiesel** [comment]
The nid is now set, once the note is created.
I assume this was done by Damien to decrease the interaction points between the backend and the frontend, but I agree that this was a big change for, what it seems like, one fewer communication points.

**Comment by ijgnd** [comment]
I just saw your pull request [Create a gui_hook for initializing buttons in Models](https://github.com/ankitects/anki/pull/746). 

This is for a different part of the UI but I wonder if you are using [Quick note and deck buttons (Fork for 2.1)](https://ankiweb.net/shared/info/1331140127). If so and if you are interested in keeping this alive and working well with Arthur's [Opening the same window multiple time](https://ankiweb.net/shared/info/1331140127) and [Keep model of add cards](https://ankiweb.net/shared/info/424778276): Do you want to take this add-on over, too? Ankiweb lists about 6k downloads for it. 

I think my add-on would benefit from some built-in hooks so that it's easier to maintain in the long run. My skills are too limited for this whereas you have already worked on adding gui hooks for buttons. 

I'm asking for selfish reasons: This would save me time in the long run and I'll have less time for Anki add-ons in the coming months. 

Also it's just in better hands if a professional developer maintains it and maybe it's interesting for you.

----

I'll upload your changes to the classes add-on to Ankiweb (at the latest) next weekend.

**Comment by hgiesel** [comment]
Hi,

I don't use the add-on, and I don't have that much interest in that feature tbh. Also I'm just super busy with the add-ons I already care for at the moment.

At the moment, I'm trying to release, what I showed off [here](https://www.reddit.com/r/Anki/comments/if6m5p/teaser_image_occlusions_clozes_and_more_at_the/). This will keep me busy for the next few weeks.

Actually it kinda shows why I'm not too interested in the add-on. I use very few note types (mostly two note types), but I try to make those as powerful/expressive as possible.

**Comment by ijgnd** [comment]
Fragen kostet ja nichts ... The screencast looks great. I'm really looking forward to the general release.

**Pull request merged**
